<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMbpxwoe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMbpxwoe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMbpxwoe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMbpxwoe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMbpxwoe\appProdProjectContainer(array(
    'container.build_hash' => 'Mbpxwoe',
    'container.build_id' => '42d928ba',
    'container.build_time' => 1528892280,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMbpxwoe');
