<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjyfvck\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjyfvck/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAjyfvck.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAjyfvck\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAjyfvck\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ajyfvck',
    'container.build_id' => '06acf6ac',
    'container.build_time' => 1529395843,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjyfvck');
