<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ticket extends \AppBundle\Entity\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'lastName', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'firstName', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'society', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'ticketNumber', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1TransportTrain', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1Breakfast', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1Visite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1TransportBus', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportBus', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Visite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Breakfast', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportTrain', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Night', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportBusNight', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionVisite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionExpo', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionArtDeco', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionDecouverte', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionGrandSite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'customer', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'facture'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'lastName', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'firstName', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'society', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'ticketNumber', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1TransportTrain', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1Breakfast', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1Visite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day1TransportBus', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportBus', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Visite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Breakfast', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportTrain', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2Night', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'day2TransportBusNight', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionVisite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionExpo', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionArtDeco', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionDecouverte', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'optionGrandSite', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'customer', '' . "\0" . 'AppBundle\\Entity\\Ticket' . "\0" . 'facture'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ticket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociety($society)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociety', [$society]);

        return parent::setSociety($society);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociety()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociety', []);

        return parent::getSociety();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketNumber($ticketNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketNumber', [$ticketNumber]);

        return parent::setTicketNumber($ticketNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketNumber', []);

        return parent::getTicketNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay1TransportTrain($day1TransportTrain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay1TransportTrain', [$day1TransportTrain]);

        return parent::setDay1TransportTrain($day1TransportTrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay1TransportTrain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay1TransportTrain', []);

        return parent::getDay1TransportTrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay1Breakfast($day1Breakfast)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay1Breakfast', [$day1Breakfast]);

        return parent::setDay1Breakfast($day1Breakfast);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay1Breakfast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay1Breakfast', []);

        return parent::getDay1Breakfast();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay1Visite($day1Visite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay1Visite', [$day1Visite]);

        return parent::setDay1Visite($day1Visite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay1Visite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay1Visite', []);

        return parent::getDay1Visite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay1TransportBus($day1TransportBus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay1TransportBus', [$day1TransportBus]);

        return parent::setDay1TransportBus($day1TransportBus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay1TransportBus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay1TransportBus', []);

        return parent::getDay1TransportBus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2TransportBus($day2TransportBus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2TransportBus', [$day2TransportBus]);

        return parent::setDay2TransportBus($day2TransportBus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2TransportBus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2TransportBus', []);

        return parent::getDay2TransportBus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2Visite($day2Visite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2Visite', [$day2Visite]);

        return parent::setDay2Visite($day2Visite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2Visite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2Visite', []);

        return parent::getDay2Visite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2Breakfast($day2Breakfast)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2Breakfast', [$day2Breakfast]);

        return parent::setDay2Breakfast($day2Breakfast);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2Breakfast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2Breakfast', []);

        return parent::getDay2Breakfast();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2TransportTrain($day2TransportTrain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2TransportTrain', [$day2TransportTrain]);

        return parent::setDay2TransportTrain($day2TransportTrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2TransportTrain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2TransportTrain', []);

        return parent::getDay2TransportTrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2Night($day2Night)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2Night', [$day2Night]);

        return parent::setDay2Night($day2Night);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2Night()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2Night', []);

        return parent::getDay2Night();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay2TransportBusNight($day2TransportBusNight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay2TransportBusNight', [$day2TransportBusNight]);

        return parent::setDay2TransportBusNight($day2TransportBusNight);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay2TransportBusNight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay2TransportBusNight', []);

        return parent::getDay2TransportBusNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionVisite($optionVisite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionVisite', [$optionVisite]);

        return parent::setOptionVisite($optionVisite);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionVisite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionVisite', []);

        return parent::getOptionVisite();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionExpo($optionExpo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionExpo', [$optionExpo]);

        return parent::setOptionExpo($optionExpo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionExpo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionExpo', []);

        return parent::getOptionExpo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionArtDeco($optionArtDeco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionArtDeco', [$optionArtDeco]);

        return parent::setOptionArtDeco($optionArtDeco);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionArtDeco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionArtDeco', []);

        return parent::getOptionArtDeco();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionDecouverte($optionDecouverte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionDecouverte', [$optionDecouverte]);

        return parent::setOptionDecouverte($optionDecouverte);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionDecouverte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionDecouverte', []);

        return parent::getOptionDecouverte();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionGrandSite($optionGrandSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionGrandSite', [$optionGrandSite]);

        return parent::setOptionGrandSite($optionGrandSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionGrandSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionGrandSite', []);

        return parent::getOptionGrandSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\AppBundle\Entity\Customer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(\AppBundle\Entity\Facture $facture = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

}
